kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-app
spec:
  selector:
    matchLabels:
      app: my-app
  replicas: 1
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: container
          image: quay.io/mdiscepo/my-app:latest
          env: 
            - name: my-key
              valueFrom:
                configMapKeyRef:
                  name: my-app-config
                  key: my-key
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  paused: false

